### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### POST request id
POST http://localhost:8080/combat-command
Content-Type: application/json

{
  "id": "A9821kNdj",
  "command": "힐 써줘"
}